### ISSUE TITLE
Error 405 (Method Not Allowed) in route /demo/todolist

### ISSUE THREAD

**Issue by Avaray** [Aslemammad/qwik-pwa-example#2]
`POST https://qwik-pwa-example.pages.dev/demo/todolist/q-data.json?qaction=tCQ608gnjnQ 405 (Method Not Allowed)`
When adding new Todo

**Comment by Aslemammad** [comment]
I see, what do you think the potential reason is?

**Comment by Avaray** [comment]
> I see, what do you think the potential reason is?

I guess somehow JSON data want's to be stored @cloudfront using POST method? As error says: it's now allowed.
I think I'm not able to help you with this.

**Comment by Aslemammad** [comment]
Sure, I'll look into this soon! Thank you so much! 

@amirsa12 might be interested.

**Comment by AmirSa12** [comment]
Normally when an HTTP method is configured for use on the server, but it has been disabled for a given URI, the server will respond with an HTTP 405 Method Not Allowed error, so There is nothing wrong with the POST request as it works fine locally. I believe it's a security/network configuration issue from the server.

**Comment by Avaray** [comment]
I wasn't sure if the cause wasn't some error in the PWA configuration. I think this issue can be closed.

**Comment by AmirSa12** [comment]
> I wasn't sure if the cause wasn't some error in the PWA configuration. I think this issue can be closed.

There is a fix here #3 , if it gets merged, the issue will get resolved

**Comment by Avaray** [comment]
> > I wasn't sure if the cause wasn't some error in the PWA configuration. I think this issue can be closed.
> 
> There is a fix here #3 , if it gets merged, the issue will get resolved

Nice
